# Generated by Django 4.2.7 on 2023-12-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoTempoSimples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=255, null=True)),
                ('dia', models.CharField(max_length=255, null=True)),
                ('uf', models.CharField(max_length=255, null=True)),
                ('entidade', models.CharField(max_length=255, null=True)),
                ('resumo', models.CharField(max_length=255, null=True)),
                ('tempo', models.CharField(max_length=255, null=True)),
                ('temp_max', models.IntegerField(default=-1)),
                ('temp_min', models.IntegerField(default=-1)),
                ('dir_vento', models.CharField(max_length=255, null=True)),
                ('int_vento', models.CharField(max_length=255, null=True)),
                ('dia_semana', models.CharField(max_length=255, null=True)),
                ('umidade_max', models.IntegerField(default=-1)),
                ('umidade_min', models.IntegerField(default=-1)),
                ('temp_max_tende', models.CharField(max_length=255, null=True)),
                ('cod_temp_max_tende_icone', models.CharField(max_length=255, null=True)),
                ('temp_min_tende', models.CharField(max_length=255, null=True)),
                ('estacao', models.CharField(max_length=255, null=True)),
                ('hora', models.CharField(max_length=255, null=True)),
                ('nascer', models.CharField(max_length=255, null=True)),
                ('ocaso', models.CharField(max_length=255, null=True)),
                ('fonte', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'previsao_tempo_simples',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('cidadeFavorita', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
